-- phpMyAdmin SQL Dump
-- version 4.0.10deb1
-- http://www.phpmyadmin.net
--
-- Servidor: localhost
-- Tempo de Geração: 25/01/2016 às 10:46
-- Versão do servidor: 5.5.46-0ubuntu0.14.04.2
-- Versão do PHP: 5.5.9-1ubuntu4.14

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Banco de dados: `goarthacom`
--

-- --------------------------------------------------------

--
-- Estrutura para tabela `digitulus_activity`
--

CREATE TABLE IF NOT EXISTS `digitulus_activity` (
  `activity_id` int(11) NOT NULL AUTO_INCREMENT,
  `activity_opportunity_id` int(11) NOT NULL,
  `activity_date` date NOT NULL,
  `activity_proposal` text COLLATE utf8_unicode_ci NOT NULL,
  `activity_answer` text COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`activity_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=186 ;

--
-- Fazendo dump de dados para tabela `digitulus_activity`
--

INSERT INTO `digitulus_activity` (`activity_id`, `activity_opportunity_id`, `activity_date`, `activity_proposal`, `activity_answer`) VALUES
(24, 65, '2015-12-15', 'Escolas - English in Chester, EC, LAL e Dominion', ''),
(27, 65, '2015-12-16', 'Encaminhei orçamento do Canadá, Toronto, ILAC, CLLC', 'Está verificando os orçamentos'),
(28, 37, '2015-09-08', 'E-mail encaminhado dia 08/09/15\r\n', 'Fechou passagem TAP 11 de setembro'),
(29, 38, '2015-09-08', 'E-mail encaminhado dia 08/09/15', 'Fechou passagem aérea Emirates para Tailândia'),
(30, 39, '2015-09-09', 'Enviei email', ''),
(31, 40, '2015-09-09', 'Encaminhei e-mail de Austrália e Irlanda\r\n', ''),
(32, 41, '2015-09-10', 'Encaminhei email com seguro CareMed', 'Falou que iria verificar - 10/09/15\r\n'),
(33, 42, '2015-09-16', 'Seguro Saúde CareMed', 'Fechou Seguro Saúde CareMed Prata'),
(34, 43, '2015-09-22', 'Encaminhei seguro CareMed\r\n', ''),
(35, 44, '2015-09-25', 'Encaminheir orçamentos de Brisbane, Melbourne, Sydney e Noosa\r\n', 'Fechou'),
(36, 45, '2015-10-06', 'Enviei orçamentos', ''),
(37, 46, '2015-10-08', 'Enviei orçamento', ''),
(38, 47, '2015-10-08', 'Enviei orçamentos', 'Fechou'),
(39, 66, '2015-12-16', 'Enviei orçamento da CareMed', ''),
(40, 49, '2015-10-09', 'Enviei opção por email da American Airlines', 'Decidiu comprar diretamente no site da American Airlines que não paga a taxa de emissão. Expliquei das vantagens de comprar conosco, mas preferiu comprar no site da AA.\r\n'),
(41, 50, '2015-10-05', 'Enviei várias opções: Alitalia, Lufthansa, Tam', 'Fechou'),
(42, 51, '2015-10-13', 'Tenho de verificar as informações com a Tatiana', ''),
(43, 52, '2015-10-13', 'Já encaminhei orçamento da Shafston e Navitas em Brisbane\r\n', ''),
(44, 53, '2015-10-16', 'Já encaminhei o CareMed', 'Fechou'),
(45, 54, '2015-10-16', 'Já encaminhei o CareMed', 'Fechou'),
(46, 55, '2015-10-19', 'Já encaminhei o CareMed', 'Fechou'),
(47, 56, '2015-10-26', 'Enviei orçamentos', ''),
(48, 57, '2015-10-29', 'Enviei passagem aérea da TAP. Uma passagem com tarifa de estudante e outra normal.', ''),
(49, 58, '2015-10-29', 'Enviei orçamento', ''),
(50, 59, '2015-11-09', 'Encaminhei opções de Cruzeiros', 'Fechou Cruzeiro da Visual no dia 18 de novembro'),
(51, 60, '2015-11-11', 'Encaminhei orçamentos da escola EC  e ALI \r\n', 'Recebeu os orçamentos e marcou com a mãe de vir na agência dia 26/11/15'),
(52, 61, '2015-11-13', 'Liguei e passei as informações sobre a categoria dos vistos, vai decidir com o amigo e entrar em contato', ''),
(53, 62, '2015-11-24', 'Informações sobre College para a esposa Mariana em Boca Raton ou Fort Lauderdale. Querem viajar com a familia sendo que a esposa estudaria e eles teriam visto de dependente.\r\nFicou de me confirmar se a esposa tem o TOFEL, mandei e-mail perguntando e estou aguardando. ', ''),
(54, 63, '2015-11-25', 'Foi enviado orçamento do seguro CareMed no período de 25/05 à 17/06', ''),
(55, 64, '2015-11-25', 'Enviei e-mail com opções da CareMed porque ele quer um seguro que cobre responsabilidade Civil\r\n', 'O cliente respondeu que esta analisando as propostas e me dar um retorno em breve'),
(56, 67, '2015-09-08', 'A Maria Flávia é mãe da Maria Luiza Guimarães de Carvalho Pereira Figueiroa, e já é cliente antiga da agência. ela veio para se informar do programa de High School para a filha e o local ela foi bem categórica na preferência pelo Canadá. Passei algumas informações básicas e amanhã vou ligar para agendar um horário, pois o atendimento de high school é bem específico e demora cerca de 2 a 3 horas.\r\n\r\n"Bom dia Maria Flávia, tudo bem? Espero que sim!\r\n\r\nGostaria de agradecer a visita ontem em nossa agência e marcar um reunião juntamente com sua filha para falarmos sobre o programa de High School. Por se tratar de um programa bem específico a reunião leva em torno de duas a três horas de duração, pois são muitos os detalhes a serem esclarecidos e debatidos. A Tatiana que trabalha conosco está justamente nesse momento no Canadá realizando pesquisas de escolas, universidades e outros parceiros, ela é especializada no atendimento de High School e estará de volta ao Brasil no final de Setembro, gostaria de agendar um horário com você já logo para a primeira semana de Outubro, me diga qual dia e horário seriam melhores que já deixo programado com a Tatiana, ok?\r\n\r\nFico a disposição e aguardo seu retorno.\r\n\r\nAtenciosamente,"\r\n', 'Mais próximo a data a cliente irá informar o melhor dia e horário para marcarmos o agendamento. Vou entrar em contato na primeira semana de outubro. '),
(57, 68, '2015-09-09', 'Cliente já tinha fechado um programa de intercâmbio na agência para Cidade do Cabo em 2009,  agora quer realizar o mesmo curso na mesma escola.\r\nCliente antigo e deve fechar essa semana ainda, passei 3 orçamentos para ele. Conversamos bastante sobre as experiências da África do Sul e tudo que ele poderia fazer no país. Hoje vou ligar para ele novamente para saber da posição. Ele está querendo realizar o pagamento a vista junto com a Marina vamos negociar um pequeno desconto na taxa de matrícula para ele fechar logo.', 'Cliente ficou de definir essa semana, tentei ligar para ele (10/09) e ainda não tive retorno, continuarei tentando. \r\nFechou 4 semanas na LAL Cidade do Cabo.\r\n\r\n'),
(58, 69, '2015-09-10', 'Cliente é amiga da Bárbara e Natália Cézari de Matozinhos, a mesma já fechou o pacote conosco, agora estamos definindo a acomodação de 5 noites em Toronto e alguns passeios turísticos.', 'Cliente fechou 5 noites em Toronto e um tour no Niagara Falls. Reservas: 16428186 e 16428228.'),
(59, 70, '2015-09-11', 'O filho da Silvânia faria um curso na Alemanha através de uma parceria com a sua universidade, porém a mesma cancelou o benefício e o estudante já havia comprado a passagem, logo quer aproveitar e fazer um curso de alemão por 12 semanas.\r\nJá envie três orçamentos para a cliente e hoje (14/09) entrei em contato e a cliente ainda não tinha uma posição, a passagem do filho é para o dia 23 de setembro. Vou esperar até a tarde, caso ela não se manifeste entrarei em contato novamente.', 'A bolsa que havia sido cancelada pela universidade foi novamente renovada, com isso o cliente não vai necessitar do curso, de toda forma a cliente agradeceu nosso atendimento e agilidade nas informações e entrará em contato em uma oportunidade futura.'),
(60, 71, '2015-09-16', 'Cliente é meu amigo e vai comprar Passagem e Seguro Saúde para filha que vai passar um tempo na Itália, na cidade de Bari. Já enviei os orçamentos do seguro-saúde e agora estou aguardando a cotação das passagens aéreas.', 'Cliente ganhou as passagens aéreas de um parente, cancelando assim as cotações realizadas. '),
(61, 72, '2015-09-18', 'Namorado da cliente realizou o programa Work and Travel na Artha, agora os dois estão querendo realizar o intercâmbio juntos e tentar de alguma maneira imigrar. ', 'No mesmo dia que eles ligaram consegui marcar uma reunião com os dois no final da tarde, eles ficaram muito animados com Brisbane pela Shafston, estou finalizando os orçamentos e enviar para eles hoje. (17/09).'),
(62, 73, '2015-09-17', 'Cliente já tinha feito uma visita anterior e voltou a entrar em contato conosco. Ela vai realizar o curso junto com mais duas amigas. Já atualizei os orçamentos e envie também valores do seguro e vamos mandar as passagens aéreas. (17/09)', 'Cliente alegou que fechará com outra agência por motivo de preço e outros mais em que ela não quis entrar em detalhe. Tinha conseguido uma promoção junto a escola do ano passado para elas, mas mesmo assim não foi suficiente. '),
(63, 74, '2015-09-17', 'Cliente foi minha companheira de trabalho no Garota Carioca e possui duas amigas que moram em San Francisco, ela tem planos de fechar o curso no final do ano. ', 'Já enviei vários orçamentos e hoje postei um link de uma escola em San Francisco no facebook dela apenas para dar uma lembrada, seguirei monitorando. '),
(64, 75, '2015-09-17', 'Cliente trabalhou comigo no Garota Carioca, já estuda francês por 2 anos e gostaria de fazer um curso no país.  Enviei alguns orçamentos e postei alguns links de escola no facebook dele também.', ''),
(65, 76, '2015-09-18', 'Cliente já realizou intercâmbio para Inglaterra e fechou um pacote turístico com a mãe para África do Sul, agora a mesma quer ir para um local onde possa estudar e trabalhar, a Austrália é a opção preferível dela.', 'Já marcamos uma reunião aqui na agência para semana que vem para mostrar os detalhes do curso e escolas recomendadas. '),
(66, 77, '2015-09-21', 'Cliente entrou em contato por e-mail e eu já encaminhei um e-mail de apresentação solicitando o telefone para poder conversar com o cliente de forma detalhada, vou aguardar o retorno para prosseguir com o atendimento. ', 'Cliente me retornar com o número do celular e imediatamente entrei em contato com ele. ficamos cerca de 40 min falando sobre os programas, semana que vem encaminharei vários orçamentos para ajudá-lo na escolha.'),
(67, 78, '2015-09-22', 'Cliente veio até a agência através da indicação da amiga Nayara Rocha que foi para a mesma escola em 2013.', 'Ela já saiu com o orçamento da escola nas mãos, com os valores do seguro, agora aguarda apenas as passagens aéreas para definir o programa. '),
(68, 79, '2015-09-23', 'Marquei para cliente vir amanha na agência.', ''),
(69, 80, '2015-09-29', 'Cliente trabalha na Vale do Rio Doce e devido a uma suposta demissão em massa ele já está preparando para realizar o intercâmbio no início do ano que vem.', ''),
(70, 81, '2015-09-29', 'A filha Nalu ligou para Tati e conversou sobre seus planos e eu conversei com a mãe, ficamos de enviar um curso com uma viagem de Top Deck no meio para casar com o perfil da estudante adequando a data que a mesma pretende viajar.', ''),
(71, 82, '2015-10-01', 'Liguei', 'Adiou'),
(72, 83, '2015-10-02', 'Conversei com ele ontem e o mesmo tem interesse de realizar o programa no ano que vem, vou selecionar alguns pacotes do site e encaminhar para ele.', ''),
(73, 84, '0000-00-00', 'Cliente já conhece o Canadá, tem 2 filhos e está planejando se mudar para o país, achou muito interessante o programa de trabalho, contudo com as vagas esgotadas vou oferecer algum College para o cliente. Já liguei pra ele e estou elaborando os orçamentos.', ''),
(74, 85, '2015-10-05', 'Cliente se interessou pelo programa de trabalho no Canadá, como as vagas foram limitadas vou passar as opções de curso na Irlanda, Austrália', ''),
(75, 86, '2015-10-06', 'Cliente se interessou pelo programa de trabalho no Canadá, como as vagas foram limitadas vou passar as opções de curso na Irlanda, Austrália', ''),
(76, 87, '2015-10-07', 'Passei todas informações para o Octávio que ficou de entrar em contato.', ''),
(77, 88, '2015-10-09', 'Cliente ligou fazendo orçamento do seguro-saúde para a mãe que tem 72 anos de idade e viajará para os Estados Unidos do dia 15/10 a 31/10, enviei os orçamentos com as opções de plano da CareMed. ', 'Como cliente ainda não retornou vou ligar para saber se vai optar por algum dos planos.'),
(78, 89, '2015-10-13', 'Cliente buscava um programa para a filha e sobrinha, que são menores, indiquei e passei alguns orçamentos do Study and Fun, estou monitorando. ', ''),
(79, 90, '2015-10-14', 'Cliente trabalha com dança inicialmente queria o programa de trabalho no Canadá, verificamos outras possibilidades na Irlanda e Austrália que ficaram bem fora do orçamento da cliente. Ela tem interesse em imigrar e assim a Diana olhará algum College no Canadá para indicar a ela.', ''),
(80, 91, '2015-10-15', 'Cliente gostaria de marcar uma reunião com a Tati para o programa de High School para a filha Alice de 16 anos. Mandei e-mail para a Tati para verificar a disponibilidade.', ''),
(81, 92, '2015-10-15', 'Cliente gostaria de realizar um curso de inglês geral ou para advogados ou nos Estados Unidos (San Diego) ou Canadá (Vancouver), ela gostaria de ir em fevereiro do ano que vem e ficar de 4 a 5 meses. marcamos uma reunião aqui na agência ao meio dia.', ''),
(82, 93, '2015-10-16', 'Quer viaja com a esposa por 6 meses para Austrália os dois pensam em trabalhar para ajudar com os custos do programa. Já enviei alguns orçamentos e estamos em fase de negociação.', ''),
(83, 94, '2015-10-19', 'Cliente viajará com a namorada e mais um ou dois casais por 4 semanas, eles gostariam de um lugar que tivesse muita natureza e que o custo-benefício fosse bom. Passei alguns orçamentos da África do Sul através do site e ele gostou muito, ficou de conversar com as pessoas do grupo para me retornar, estou monitorando o cliente. ', ''),
(84, 95, '2015-10-20', 'Conversei com a mãe dele a Sra. Irany devido o filho não ter tempo pela carga pesada de estudos. parece que ela já havia conversado com alguma atendente aqui na Artha mais ninguém a reconheceu então realizarei o atendimento. Já passei algumas opções de programas e a mesma disse que analisará junto com o filho para logo marcar uma visita aqui na agência. Estou monitorando. ', ''),
(85, 96, '2015-10-21', 'Cliente ligou para fazer cotação de seguro-saúde, passei todos os planos da CareMed com apólice e cobertura mas cliente optou por ficar com um seguro bem mais barato do cartão de crédito mesmo sabendo da diferença entre eles. ', ''),
(86, 97, '2015-10-22', 'Cliente ligou para fazer cotação de seguro-saúde, passei todos os planos da CareMed com apólice e cobertura, cliente ainda não definiu, estou monitorando através do telefone e e-mail. ', ''),
(87, 98, '2015-10-26', 'Cliente inicialmente gostaria de ir para o Canadá pois tem uma amiga que já mora em Calgary. Contudo pelo tempo e pelo que conversamos no telefone ela tem interesse de ficar 24 semanas no mínimo e também gostaria de trabalhar, falei um pouco das opções mas vamos aprofundar mais amanhã em reunião agendada para as 15 horas.', ''),
(88, 99, '2015-10-30', 'Cliente ira viajar para Madrid e Barcelona entre os dias 12/11 - 02/12, já envie as nossas opções de seguro para análise, hoje vou entrar em contato para saber do cliente. ', ''),
(89, 100, '2015-11-03', 'Cliente está procurando algum curso na área de Administração para a irmã, focado ou somente no trabalho ou estágio remunerado, vou passar algumas opções no Canadá, que a Diana me indicou. ', ''),
(90, 101, '2015-11-04', 'Cliente gostaria de ir para Melbourne por já ter amigos morando na cidade, realizei alguns orçamentos para ela e já entrei em contato para confirmar o recebimento, continuarei acompanhando através de e-mails e telefonemas periódicos. ', ''),
(91, 102, '2015-11-04', 'Cliente gostaria de ir para Irlanda por um período de 24 semanas, já agendei um horário amanha para conversarmos melhor sobre os detalhes do programa. ', ''),
(92, 103, '2015-11-04', 'Cliente é pai da Giulia, amiga da Ana Luíza que fechou um programa de College no Canadá com a Diana, já encaminhei todas as informações para ela poder dar seguimento no atendimento. ', ''),
(93, 104, '2015-11-09', 'Cliente está em dúvida entre Irlanda e Austrália, conversamos bastante por telefone e já enviei vários orçamentos, cliente parece não ter ainda uma quantia suficiente para realizar o programa. Atendimento será monitorado. ', 'Cliente realizou pesquisa em várias agências mas achou tudo muito caro e resolveu realizar a viagem por conta própria, passei o contato para o Heitor auxiliá-la no processo do visto para os Estados Unidos. '),
(94, 105, '2015-11-12', 'Mandei três opções de seguro CareMed para cliente avaliar, a mesma viajará no dia 24/11, entrarei em contato novamente para verificar a posição da cliente. ', ''),
(95, 106, '2015-11-13', 'Cliente gostaria de ir para Gold Coast com a namorada, o mesmo já tem um amigo que mora por lá e iria ajudá-los. Já envie três orçamentos e marcamos uma reunião para o dia 19/11 aqui na Agência para definirmos a escola. ', ''),
(96, 107, '2015-11-18', 'Cliente teve indicações de amigos próximos sobre a escola ILAC, vou enviar alguns orçamentos para ela hoje ainda, ela mora em Ouro Branco e não virá a Belo Horizonte com muita frequência.', ''),
(97, 108, '2015-11-23', 'Cliente estava em dúvida com relação a Austrália, Inglaterra e Estados Unidos, mas conforme nossa conversa ele vai optar pela Austrália por poder trabalhar legalmente. Marquei uma reunião na sexta-feira às 13 horas. ', ''),
(98, 109, '2015-11-30', 'Viagem para a Holanda de 13/12/16 - 06/01/16\r\n', ''),
(99, 110, '2015-11-30', 'Informações sobre visto, passei a indicação ao Heitor.', ''),
(100, 111, '2015-12-01', 'Cliente vai estudar na Queensland University of Tecnology em parceira com a PUC Minas do dia 10 de fevereiro a 10 de julho e está procurando por uma acomodação para todo tempo de curso. Passei os valores da Shafston Mansions para ela e estou aguardando retorno. ', ''),
(101, 112, '2015-12-01', 'Passei orçamentos', 'Fechou na sexta-feira, 11 de dezembro'),
(102, 113, '2015-12-15', 'Carga de CA$ 1000 no VTM', 'Fechou'),
(103, 114, '2015-12-07', 'Venda de AU$ 2500.00 em espécie.', 'Vendido'),
(104, 115, '2015-12-15', 'Recarga de CAD$ 890.00 no VTM.', 'Vendido'),
(105, 116, '2015-12-16', 'Recarga de cartão VTM € 800,00.', 'Vendido.'),
(106, 117, '2015-12-17', 'Recarga de € 200.00 no cartão VTM.', 'Vendido.'),
(107, 118, '2015-09-18', 'Enviei orçamentos: \r\n- Seneca College\r\n- Georgian College\r\n- George Brown \r\n- Fanshawe College\r\n- Humber College\r\n', 'Optou pelo Fanshawe College.\r\nCurso de Inglês iniciando em Março.\r\nAdvanced Diploma iniciando em Setembro.\r\n1. Advanced Diploma em Computer Programmer Analyst (3 anos, com co-op).\r\n2. Especialização: Game Development - Advanced Programming.'),
(108, 118, '2015-09-22', '\r\n', 'Optou pelo Fanshawe College. Curso de Inglês iniciando em Março. Advanced Diploma iniciando em Setembro.'),
(109, 119, '2015-12-17', 'topdeck - roman trail e passagem aérea ', 'positiva - fechou 1 dia depois '),
(110, 120, '2015-12-21', 'Proposta bacana e preço bom.', 'Cliente fechou.'),
(111, 121, '2015-11-10', 'Pacote para esquiar nos Estados Unidos', 'Passei pra ele a cotação de Breckenridge com carro.'),
(112, 122, '2015-12-22', 'Ana Batista Garcia - Os valores de seguro Ouro de Cobertura Ilimitada para Europa pelo período de 27/12/2015 a 10/02/2016 (7 Semanas), são:  USD 280,00 (4,069) = R$1.139,32 (cobertura ilimitada)\r\n\r\nClaudia e Fernando - Os valores de seguro Ouro de Cobertura Ilimitada para Europa pelo período de 27/12/2015 a 17/01/2016 (3 Semanas), são: USD 132,00 (4,069) = R$537,10 (cobertura ilimitada)\r\n\r\nSendo assim o valor total para toda família é R$2.213,53', 'Pago'),
(113, 123, '2015-02-09', 'Orçamentos diversos', 'A cliente  e família optaram por High School em Bournemouth Inglaterra e curso de alemãoi'),
(114, 124, '2015-05-01', 'Orçamento SELC Canadá 25 semanas', 'Fechou'),
(115, 125, '2015-08-29', 'High School 2016 – Estados Unidos Público – promoção para inscrição até 31 de agosto', ''),
(116, 126, '2015-02-09', 'Orçamentos', 'Fechou High School Bournemouth'),
(117, 127, '2015-01-20', 'Orçamentos', 'O cliente fechou VEC'),
(118, 128, '2014-08-08', 'Enviei email perguntando se ela está interessada em cursos de mestrado ou especialização e seu nível de inglês', 'Não houve resposta'),
(119, 129, '2015-12-18', 'Curso de 4 semanas na escola Enforex em Barcelona. Acomodaçao em residência estudantil.', 'Cliente fechou!'),
(120, 128, '2014-10-16', 'Ofereci UCLA Extension curso de engenharia', 'Ficou de fechar na terça-feira 21 de Outubro de 2014, às 18:30'),
(121, 128, '2014-10-21', 'Encontro com a Marina e a Eduarda', 'Fechou'),
(122, 130, '2015-09-27', 'Enviei orçamentos', 'Aguardando resposta'),
(123, 131, '2015-01-20', 'Orçamentos', 'Cliente fechou Wimbledon'),
(124, 132, '2015-03-15', 'Transferência de atendimento de Tatiana para a Rivane', ''),
(125, 133, '2015-05-08', 'Orçamentos', 'Fechou Shafston'),
(126, 134, '2015-07-20', 'Ciente se interessou por Experience Hampstead', 'Fechou Experience Hampstead'),
(127, 135, '2015-07-20', 'Ofereci Experience Hampstead', 'Fechou Experience Hampstead'),
(128, 136, '2015-07-29', 'Orçamento', 'Fechou High School Canadá no distrito de Delta'),
(129, 137, '2015-08-10', '"dia 16 Set - Diana enviou email com informativo e orçamento:\r\n- Moraine Valley Community College em Chicago, Estados Unidos.\r\n- UCLA Extension em Los Angeles, Estados Unidos.\r\n\r\ndia 18 Set - Diana enviou email:\r\n- Seneca College, em Toronto - informativo e opções de cursos\r\n- Georgian College, em Barrie - informativo\r\n\r\ndia 21 Set - Diana enviou email:\r\n- Georgian College, em Barrie - opções de cursos e respostas para as dúvidas que carol enviou por email"\r\n', '"Então, como te disse, acho que Barrie não é minha primeira opção... achei a cidade muito longe de Toronto e não sei se é exatamente o que eu estou procurando. Como conversamos no whatsapp, fico no aguardo de outras opções no Canadá, preferencialmente em Toronto e opções nos EUA, sonhando alto, quem sabe NYC.\r\nAndei pensando, e MIAMI também talvez seja uma opção, não é minha cidade favorita (muito longe disso), mas acho que por oportunidades profissionais talvez seja viável...\r\nE como falei hoje, o custo de Design Management me interessa MUITO, se conseguir algo nessa linha de estudo de Design Thinking e Marketing misturado com Business seria muito massa! Enquanto você procura, também to tentando achar algo que me interesse assim fica mais fácil pra você e pra mim também ne? J\r\n \r\nDe qualquer maneira, veja abaixo as perguntas que elaborei sobre Barrie:\r\n     Could you please clarify how long it takes from Georgian College to Downtown Toronto by public transportation? I saw on google maps and it seems to be a long trip, more than 3 hours, is that correct? \r\n    During the course I need to maintain myself in the city by working. Is it highly possible for me to get a job as soon as I arrive there in the city? \r\n        o   What is the average salary per hour for this kind of job? \r\n        o   Will I be able to conciliate my studies with work? Or will the course demand my exclusive dedication to it?  \r\n    Please let me know the actual possibility of getting a job at a company on the area of foreign exchange or business administration during my course and after I’m finished? \r\n    Does Georgian College offers any courses specialized on design thinking or market for business?"\r\n'),
(130, 137, '2015-08-10', 'Cliente transferido de Tatiana para Diana', ''),
(131, 138, '2015-08-10', 'UCLA Certificate, Moraine Valley, Philadelphia, Vancouver (4 meses de inglês com estágio e UBC de 3 semanas no final), Shafston', '"Em 16 de SET Diana enviou email com informativo e orçamentos: - Moraine Valley Community College em Chicago, Estados Unidos. - UCLA Extension em Los Angeles, Estados Unidos. \r\nEm 23 de SET Diana enviou email com informativo e orçamento da Shafston."\r\n'),
(132, 138, '2015-08-10', 'Cliente transferido de Tatiana para Diana', ''),
(133, 139, '2015-08-11', 'Chegou a emitir a boleto do PagSeguro do curso de Cork', 'Chegou a emitir a boleto do PagSeguro do curso de Cork mas não pagou, disse que tinha de verificar o calendário na escola'),
(134, 140, '2015-08-11', 'Orçamentos', 'Ligou, viu no site, mandei vários e-mails, quer ir ano que vem, passar 3 meses, em casa de família. Pediu cotação sem passagens'),
(135, 141, '2015-08-12', 'Deixei a própria brochura do programa para ela', ''),
(136, 142, '2015-08-12', '"Gostaria de trabalhar por seis meses no EUA para aperfeiçoar meu inglês. 1 EMAIL\r\nVocês possuem algum programa? ESTADOS UNIDOS - Vou fazer 30. Meu nível é básico, estou fazendo curso de inglês particular e ele me falou que passo para intermediário antes da viagem. Quero ir em fevereiro. Me falaram que você pode trabalhar na escola para conseguir o social security e depois ir  trabalhar em outro lugar. Isso procede?"', 'Resposta'),
(137, 142, '2015-08-17', 'Geralmente você só pode trabalhar na escola/ campus. Você terá o social. Para o curso de inglês, você não tem autorização para trabalhar fora. Alguns programas quando vc forma, vc pode ficar mais 1 ano trabalhando na área que formou, mas não é o caso do curso de inglês\r\n', '"Mas preciso melhorar meu inglês então quero fazer o curso mas queria trabalhar também pois se não vou acabar me apertando. \r\nAgora você me indicaria algum outro lugar para ir?Que de para estudar e trabalhar? Gostaria de marcar um horário com você. Você teria qual horário livre?\r\nDevo ficar em Nashua, pois tem um primo que mora lá.Então queria algo mais perto da cidade. Nashua é perto de Boston "\r\n'),
(138, 143, '0000-00-00', '', ''),
(139, 142, '2015-08-17', '"Sou formada em direito e já exerço a profissão aqui,\r\n \r\nMeu primo conseguiu um trabalho para mim em um escritório de advocacia.\r\nNeste caso não vou poder trabalhar então?\r\nTeria alguma coisa na minha área  que poderia fazer?"\r\n', '"você pode fazer um programa de estágio nesse escritório, até 32 anos, eles tem que te remunerar, e fazer o plano do estágio, você não poderá estudar inglês. e você terá que ter um inglês avançado então tem que estudar mais.\r\nOk.\r\nMas preciso melhorar meu inglês então quero fazer o curso mas queria trabalhar também pois se não vou acabar me apertando.\r\nAgora você me indicaria algum outro lugar para ir?\r\nQue de para estudar e trabalhar?\r\nOlá Michelle,\r\nvou procurar algo na região que vc tem aonde ficar, pois é uma super economia, mas se eu não encontrar nenhuma opção, te envio outros locais.\r\nTati\r\nOk! Pode ser em Boston também pois meu primo falou que é pertinho!\r\nE ele falou que vai deixar um carro dele comigo o que eu acho que ira me facilitar muito!\r\n \r\nMas assim que souber me avisa pois quero resolver isso antes por causa do visto de estudante.Eu já tenho o visto de turista. Isto ajuda? Michele,\r\nSem dúvidas é ótimo já ter o visto de turista, mas é importante se preparar com o maior cuidado sempre. Vc acredita que uma cliente, Renata, tinha o visto de turista e acabou tendo o de estudante negado? aí eu tive que refazer todo o processo do visto, e aí ela tirou o visto....até hoje não entendi o que ela arrumou para ter esse visto negado, risos....mas no fim tudo deu certo e ela foi para NYC....\r\nvou procurar todas as possibilidades na região e aí marcamos.\r\nTati Bom dia!Ok Você sabe me informar se teria a possibilidade só de trabalho também?\r\n Mas minha prioridade é estudar e trabalhar naquela possibilidade que vc falou!\r\nBom dia.Tatiana, já tem alguma posição?Você tem ideia de quanto ficaria tudo?"\r\n'),
(140, 144, '2015-08-14', 'Ela marcou de vir aqui na primeira semana de setembro e não veio', ''),
(141, 143, '2015-11-23', 'Enviado orçamento da escola Language Pacifica e Golden Gate', 'Optou por 4 semanas na Language Pacifica.'),
(142, 145, '2015-10-01', 'Era cliente da Tati, que tinha fechado e depois cancelou. Tati indicou 4 meses de Inglês no Georgian College, em Barrie, Canadá, embarcando em Janeiro (para aproveitar a passagem ja comprada no ano anterior). ', 'Fechou 4 meses de Inglês no Georgian College, começando em Janeiro e terminando em Abril.'),
(143, 146, '2015-10-23', 'Conversamos sobre todas as possibilidades de Imigração pro Canadá e Austrália. Tem preferencia por Australia (Melbourne, Sydney ou Gold Coast) pois ja morou lá. Está fazendo consultoria para aplicar pro skilled visa mas como não trabalha na área gostaria de outra opção. Solicitou cursos técnicos e enviei algumas opções TAFE.', 'Optou por ter um gap year e viajar pelo mundo ao invés de fazer o curso.'),
(144, 147, '2015-08-17', 'Achei as perguntas muito estranhas e não típicas de uma adolescente – ficou bem parecido com alguém somente querendo saber preço', 'Ficamos conversando por e-mail'),
(145, 148, '2015-12-21', 'UBC - Vancouver\r\n\r\nEnglish for Global Citizen', ''),
(146, 149, '2015-12-21', 'Enviei orçamento para Shafston, mesmo orçamento do Gustavo Mirai.', ''),
(147, 150, '2015-12-21', 'Enviei opções e orçamento, o mesmo do Gustavo.', 'Aguardando'),
(148, 151, '2015-09-11', 'Opções e orçamentos foram enviados. ', 'Achou as opções acima do valor.'),
(149, 151, '2015-11-17', 'Posteriormente retomou contato com interesse em Perth, onde conseguiu um possibilidade de emprego e já possui contatos. Solicitou opções de Certificate e Diploma na área de Business e Marketing. Enviei opções em várias instituições de Perth. ', 'Optou pelo Certificate IV em Marketing na TAFE (Central Institute of Technology).'),
(150, 152, '2015-09-16', 'Enviei email com informativo e orçamentos: \r\n- Moraine Valley Community College em Chicago, Estados Unidos. \r\n- UCLA Extension em Los Angeles, Estados Unidos. \r\n- Informativo e orçamento da Shafston, Brisbane.\r\n- UBC em Vancouver, Canadá.', 'Em conversa por telefone Eduardo disse estar mais interessado na Australia. Porém cliente parou de retornar as ligações e atender o telefone. Não respondeu mais as mensagens do whats app. \r\n'),
(151, 130, '2015-09-23', 'Em conversa com a Tati ela me explicou:\r\nO direito americano, canadense e australiano é chamado commom law, e o nosso é civil law. \r\nEntão o direito de família será muito distinto do que ela aprendeu aqui, e o que ela aprender lá não poderá ser aplicado aqui. O direito autoral, apesar da matéria hoje ser mais unânime devido a internet, tanto as leis quanto a aplicabilidade e a punidade seriam diametrais ao nosso direito. Se ela for aplicar no Brasil é importante pensar em Itália, Alemanha, França. Para o direito a primeira providência é o aprendizado do idioma, pois o curso de direito exige um nível maior de inglês do que alguns outros cursos. A alternativa é o direito comparado ou direito internacional. Se não interessar e quiser a área cível (família ou autoral) é preciso que ela decida um dos dois para pesquisarmos qual país é mais avançado nessa área. Cada especialidade varia muito.\r\nDireito internacional: a Alemanha é referência.\r\nEla precisa decidir: \r\n- Se quer em país de língua inglesa: common law – escolher outro ramo do direito\r\n- Manter o ramo que ela deseja mas definir autoral ou família. Ai buscaremos o país referência nesse direito que segue o civil law – ou origina-se do direito romano. Mas aí tem a chance de ser em outro idioma e ela teria que fazer no mínimo 6 meses de idioma.', 'Após reunião no dia 30/09 comigo e com a Tati a cliente optou pela UCLA, cursos nas áreas de Artes (cenografia, marketing, cinema) ou paralegal. Precisa de 2 meses de inglês antes.'),
(152, 130, '2015-10-05', 'Enviado Informativos e opções de cursos na UCLA.', 'Optou por não fazer o intercâmbio neste momento, talvez mais pra frente.\r\n'),
(153, 153, '2015-12-17', 'Enviei opções em Toronto e Vancouver.', 'Aguardando resposta.\r\nSolicitou indicação de professor particular de inglês - retorno pendente'),
(154, 154, '2015-11-19', 'Enviei o seguinte:\r\n1. Fanshawe College, em London - informativo e opção de curso.\r\n2. Centennial College, em Toronto\r\nCurso: Biomedical Engineering Technology (3 anos, com co-op) \r\nCurso: Practical Nursing (2 anos, sem co-op) \r\nCurso: Biotechnology Advanced (3 anos, com co-op) \r\n3. Georgian College, em Barrie: informativo e opção de curso \r\n4. Seneca College, em Toronto - informativo \r\nCurso: Biotechnology - Advanced (3 anos, com co-op)  - \r\nCurso: Practical Nursing (2 anos, sem co-op) ', 'Aguardando retorno'),
(155, 155, '2016-01-04', 'Vou fazer orçamentos da St Giles - Inglês Geral e Platinum e outras escolas', ''),
(156, 156, '2016-01-05', ' Intensive English Comunication Program (IECP)\r\n\r\n    Winter\r\n    Section B\r\n    Dates: 01/02/2016 to 25/02/2016\r\n\r\nValores:\r\n\r\n    Taxa de Transferência internacional: US$100,00\r\n    Taxa de Matricula: US$150,00\r\n    Taxa de Serviço UCLA: US$500,00\r\n    Valor do Curso: US$1985,00\r\n    Taxa de Auxilio de Colocação em Acomodação: US$100,00\r\n    2 Seguros de Cobertura Ilimitada para 1 mês: 2 x US$169,00 = US$338,00\r\n    1 Seguro Infantil Cobertura de US$100.000,00 -  1 mês: US$211,00\r\n        Total: US$3.384,00\r\n\r\nForma de Pagamento:\r\n\r\n    Entrada 03/09/2015: US$635,00 (3,983) = R$2.529,20\r\n    Pagamento Final até dia 15/01/2016:\r\n        US$200,00 (4,185) = R$837,00 - Valor não incidente de IOF\r\n        US$2.549,00 (4,185) = R$10.667,56 + 6,38% = R$11.348,15\r\n            Total Final: R$12.185,15', 'Pagamento Efetuado'),
(157, 157, '2015-12-03', 'Mandei orçamento com opções de cursos de 5 meses, 5,5 meses e 6 meses (mais 2 meses de férias). Escola: Shafston. ', 'Ele optou pela opção de 5,5 meses de curso (22 semanas), com visto de 30 semanas.'),
(158, 158, '2016-01-07', 'Tatiana vai passar as informações', ''),
(159, 155, '2016-01-08', 'No dia 07/01 encaminhei orçamentos da escola St Giles San Francisco', 'Oi Joyce,\r\n\r\nAcuso recebimento de seu email com o orçamento solicitado.\r\nVou analisar junto com o Mateus e com minha filha.  Volto a falar com você o mais rápido possível.\r\nAgradeço mais uma vez sua atenção!'),
(160, 159, '2015-12-03', 'Enviei opções na Shafston:\r\n- 20 semanas de curso (28 semanas de visto)\r\n- 22 semanas de curso (30 semanas de visto)\r\n- 24 semanas de curso (32 semanas de visto)\r\nAcomodação: quarto triplo 1 mês', 'Optou por 22 semanas de curso (30 semanas de visto)\r\nData de Início: seg, 4 de jul de 16\r\nData de Termino: sex, 27 de jan de 17'),
(161, 160, '2015-11-09', 'Enviei opções de curso do Fanshawe College, Diploma e Advanced Diploma de 2 ou 3 anos, com coop, que daria a opção de conseguir work permit e residencia apos terminar o curso.', 'Optou por ir pra Australia por conta propria, pelo visto 476 que é para engenheiros recem formados.'),
(162, 161, '2015-10-23', 'Enviei opções de cursos de  Diploma em dança na Nova Zelandia e cursos de Inglês na NZ e Australia (Perth, Adelaide, Brisbane). Busquei opções no Canadá mas não encontrei nada em dança de acordo com o que ela queria.', 'Achou os cursos de Diploma acima do valor que ela pode gastar. Continua com interesse nos cursos de inglês, principalmente em Brisbane ou Melbourne onde ela consegue acomodação com conhecidos. Até agora gostou mais da opção da Shafston com curso de 5 meses e visto de 7 meses. Pretende embarcar no final de julho ou agosto.'),
(163, 162, '2015-12-01', 'Solicitei mais informações sobre a cliente, que me respondeu. Expliquei um pouco sobre o funcionamento de High School e disse que entraria em contato no inicio de 2016.', ''),
(164, 163, '2015-12-04', 'Enviei opções de cursos de 4 semanas em Vancouver e Toronto, e informativos. Enviei opções de acomodação estudantil e casa de familia. Enviei promoções da Kaplan e EC válidas até fim de janeiro de 2016.', '07/01/16: Sobre os orçamentos é mais ou menos isso mesmo! A gente so esta tentando confirmar a data com nossas empresas para resolvemos.. E assim q tivermos uma resposta concreta entro em contato ok? Se eu for em BH te ligo pra passar ai na agencia tambem! '),
(165, 164, '2015-12-16', 'Enviei 4 opções que contemplam as principais cidades.', 'Selecionou 2 opções favoritas e pediu detalhes das outras cidades (detalhes enviados em 05/01).'),
(166, 165, '2015-12-02', 'Enviei opções de 5 semanas em:\r\n- Reino Unido: IH Aberdeen, English in Chester, Anglo-Continental e Wimbledon School of English\r\n- Malta: EC Malta, IH Malta, Gateway e LAL', 'Gostou mais das opções de Malta. Achou as opções de Reino Unido caras. Está idecisa sobre Malta por ser uma ilha e mais dificil de viajar no fim de semana. Pensou em Irlanda (respondi que tem muito brasileiro e um publico mais jovem). Ofereci Stafford House (em Cambridge e Canterbury). Ainda não fiz orçamento desta opção. Cliente não retornou se tem interesse ou se quer mesmo Irlanda.'),
(167, 166, '2015-10-30', 'Enviei opção em Manchester, que é a maior cidade de New Hampshire. A Southern New Hampshire University fica ha meia hora de carro de Nashua ou Windham. Enviei também opção em Boston-University of Massachusetts Boston.', 'Disse ter gostado da opção de Southern New Hampshire University. Após eu ter enviado a opção de Boston, não retornou mais aos telefonemas e emails. '),
(168, 167, '2015-11-16', 'Enviei opções:\r\n\r\nNa área de Arquitetura:\r\n- Centennial College (em Toronto) - \r\nArchitectural Technology (Co-op) - 3 anos \r\n- Georgian College (em Barrie) - Architectural Technician (co-op) - 2 anos \r\nArchitectural Technology (Co-op) - 3 anos\r\n\r\nNa área de Finanças:\r\n- George Brown College (em Toronto) - Business Administration - Finance Program (with work experience)  - 3 anos \r\n- Sheridan College (Mississauga) - Business Administration – Finance (Co-op) - 3 anos', 'Se interessou pelo curso de finanças do George Brown. Enviei mais informações sobre este curso: Informativo completo sobre o George Brown, o guia do estudante internacional e informações sobre o curso de Business Administration-Finance. Cliente gostou desta opção, está indo denovo para o canadá em jan estudar inglês para fazer o IELTS.  Solicitou informações sobre forma de pagamento e enviei. Depois disso não retornou mais.'),
(169, 168, '2015-12-14', 'Enviei opções em Toronto: Hansa, ILAC, Kaplan, EC, Eurocentres.\r\nA única escola que oferece cursos noturnos é a HANSA, que também é a que possui os melhores valores.\r\n', 'Gostou das opções. Disse avaliar com a esposa se os 2 irão mesmo ou somente ele. Contato feito por whatsapp na maior parte do tempo.'),
(170, 169, '2016-01-04', 'Estou verificando a possibilidade da cliente fazer este curso. Contatei a UCLA para saber se aceitam estudantes internacionais neste curso. ', ''),
(171, 170, '2016-01-08', 'Enviei opções de cursos para o casal na UCLA. ', 'Aguardando'),
(172, 171, '2016-01-06', 'Enviei opções em Queensland, Victoria e Adelaide.', 'Aguardando.'),
(173, 172, '2015-11-16', 'High School Waterloo (Canadá)\r\n- Inicio: 01 Setembro de 2016\r\n- Fim: 30 de Janeiro de 2017', 'Vendido'),
(174, 173, '2015-11-11', 'Mini High School Queensland\r\n- Inicio: 22 de Agosto de 2016\r\n- Fim: 09 de Dezembro de 2016\r\n', 'Vendido'),
(175, 174, '2016-01-14', '', ''),
(176, 175, '2016-01-15', '        Seguro Prata - Com upgrade para Ouro (20/01/2016 a 24/02/2016) - 37 Dias\r\n            Valor: US$180,00 (4,177) = R$751,86 + 6,38% = R$799,82\r\n\r\n        2 Semanas GE15 Experience English (18/01/2016 a 29/01/2016)\r\n            Valor: 2 x £199,00 = £398 (5,997) = R$2.386,80 + 6,38% = R$2.539,08\r\n\r\nTotal: R$3.342,91', 'Ok...Realizou o deposito\r\n'),
(177, 176, '2016-01-15', '        Seguro Bronze - Com upgrade para Ouro (20/01/2016 a 24/02/2016) - 37 Dias\r\n            Valor: US$155,00 (4,177) = R$647,43 + 6,38% = R$688,74\r\n\r\n        1 Semana GE15 Experience English (18/01/2016 a 22/01/2016)\r\n            Valor:  £199 (5,997) = R$1193,40 + 6,38% = R$1269,54\r\n\r\nTotal = R$1.958,53\r\n', 'Vendido'),
(178, 177, '2016-01-15', 'Enviei opções na Shafston: - 20 semanas de curso (28 semanas de visto) - 22 semanas de curso (30 semanas de visto) - 24 semanas de curso (32 semanas de visto).\r\nAcomodação 4 semanas: quarto duplo sem vista para o rio.', ''),
(179, 174, '2016-01-18', 'Enviei opções de cursos em Ontário (Canadá):\r\n- Fanshawe College\r\n- George Brown College\r\n- Seneca College\r\n\r\nEnviei opções de cursos na Colúmbia Britânica (Canadá):\r\n- Vancouver Island University\r\n- University of British Columbia\r\n\r\nEnviei opções de cursos em Perth (Australia)\r\n- TAFE', ''),
(180, 178, '2016-01-18', 'Enviei vários pacotes do goArtha nos EUA (NY e Califórnia) - 1 mês.\r\nEnviei orçamentos Australia: SACE em Adelaide e Melbourne e Shafston em Brisbane - 14 semanas de curso.', ''),
(181, 179, '2016-01-19', '\r\nMALVERN HOUSE\r\nISI\r\nEMERALD\r\nCES', ''),
(182, 180, '2016-01-15', 'CareMed Bronze 32 dias', 'Fechou'),
(183, 181, '2016-01-20', 'Expliquei que não é possível estudar inglês e trabalhar no Canada, dando as opções de Australia, NZ e Irlanda. Cliente optou pela Australia. Enviei orçamentos das escolas Shafston em Brisbane e SACE em Adelaide e Melbourne, para duração de 1 ano.', 'Aguardando retorno.'),
(184, 182, '2016-01-21', 'Enviei o mesmo orçamento do Gustavo e Carlos Augusto - Shafston, 5,5 meses de curso, 7,5 meses de visto.', 'Aguardando posição do cliente.'),
(185, 183, '0000-00-00', '', '');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
